catalog/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.conf.urls import include
import catalog.views 


urlpatterns = [
    path('softwarerequest/', views.CreateSoftwareRequest.as_view(), name='softwarerequest-create'),
    path('', TemplateView.as_view(template_name='dashboard/home.html'), name='home'),
    path('accounts/', include('allauth.urls')),
    path('mysoftware/', views.AvailableSoftwareByUser.as_view(template_name = 'catalog/availablesoftwarelicense.html'), name='mysoftware'),
    path('availablesoftware/', views.AvailableSoftwareByUser.as_view(), name='availablesoftware'),
    path('software/<int:pk>', views.SoftwareDetailView.as_view(), name='software-detail'),
    path('softwarerequests/manage/', views.SoftwareRequestsManager.as_view(), name='softwarerequests-manager'),
    path('softwarerequests/<uuid:pk>', views.SoftwareRequestsDetailView.as_view(), name='softwarerequests-detail'),
    path('softwarerequests/<uuid:pk>/delete/', views.DeleteRequestingSoftware.as_view(), name='softwarerequests-decline'),
    path('softwarerequests/<uuid:pk>/accept/', views.accept_button, name='softwarerequests-accept'),
    path('softwarerequests/<uuid:pk>/process/', views.process, name='softwarerequests-forward'),
    path('mysoftware/<int:pk>/', views.softwarelicensekeys, name='mysoftware-instances'),
]
#software manager
urlpatterns += [
    path('software/manage/', views.SoftwareManager.as_view(), name='software-manager'),
    path('software/create/', views.CreateSoftware.as_view(), name='software-create'),
    path('software/<int:pk>/update/', views.UpdateSoftware.as_view(), name='software-update'),
    path('software/<int:pk>/delete/', views.DeleteSoftware.as_view(), name='software-delete'),
]
#software instance manager
urlpatterns += [
    path('softwareinstance/create/', views.CreateSoftwareInstance.as_view(), name='softwareinstance-create'),
    path('softwareinstance/<uuid:pk>/update/', views.UpdateSoftwareInstance.as_view(), name='softwareinstance-update'),
    path('softwareinstance/<uuid:pk>/delete/', views.DeleteSoftwareInstance.as_view(), name='softwareinstance-delete'),
]

softwaremanagement/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

class SoftwareType(models.Model):
    name = models.CharField(max_length=100, help_text='Enter the type of software')
    def __str__(self):
        return self.name

class Software(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(max_length=1000, help_text='Enter a description of the software')
    softwaretype = models.ManyToManyField(SoftwareType, help_text='Select software types')

    @property
    def any_avaiable(self):
        for copy in self.softwareinstance_set.all:
            if (copy.renewal_date and date.today() <= copy.renewal_date) or copy.self.status == 'a':
                return True
        return False

    class Meta:
        permissions = (("canmake", "Abiity to add a software"),)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('software-detail', args=[str(self.id)])

class SoftwareInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this software instance')
    software = models.ForeignKey('Software', on_delete=models.CASCADE, null=True)
    renewal_date = models.DateField(null=True, blank=True)
    renewal_cost = models.FloatField()
    license_key =models.CharField(max_length=26)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    STATUS = (
        ('a', 'Available'),
        ('u', 'Unavailable'),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default='a',
    )

    @property
    def is_available(self):
        if self.status == 'a':
            return True
        return False
    @property
    def is_overdue(self):
        if self.renewal_date and date.today() > self.renewal_date:
            return True
        return False

    class Meta:
        ordering = ['renewal_date']

    def __str__(self):
        return f'{self.id} ({self.software.title})'

class RequestingSoftware(models.Model):
    name = models.CharField(max_length=300)
    email = models.EmailField(max_length=300)
    department = models.CharField(max_length=300)
    reason = models.TextField(max_length=1000, help_text='Enter a reason for why you need the software')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this software instance')
    software = models.ForeignKey('Software', on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    send_date = models.DateField(null = True, blank= True)
    class Meta:
        ordering = ['send_date']

    def __str__(self):
        return f'{self.id} ({self.software.title})'

catalog/forms.py
from .models import RequestingSoftware, Software, SoftwareType, SoftwareInstance
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import SoftwareInstance

class ApplyLicenseKeyForm(forms.ModelForm):
    def __init__(self, mysoftware, *args, **kwargs):
        super(ApplyLicenseKeyForm, self).__init__(*args, **kwargs)
        self.fields['license_key'] = forms.ModelChoiceField(queryset = SoftwareInstance.objects.filter(software = mysoftware), to_field_name='license_key')
    class Meta:
        model = SoftwareInstance
        fields = ('license_key', )

catalog/views.py
from urllib import request
from django.shortcuts import render
from .models import RequestingSoftware, Software, SoftwareType, SoftwareInstance
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from catalog.models import Software
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse

import requests
import datetime
from catalog.forms import ApplyLicenseKeyForm
from django.views.generic.edit import FormView

def get_referer(request):
    referer = request.META.get('HTTP_REFERER')
    if not referer:
        return None
    return referer

class MySoftwareByUser(LoginRequiredMixin, generic.ListView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = SoftwareInstance
    template_name='catalog/mysoftware.html'
    paginate_by = 10
    def get_queryset(self):
        return SoftwareInstance.objects.order_by('software').order_by('renewal_date')
        
class AvailableSoftwareByUser(LoginRequiredMixin, generic.ListView):
    model = Software
    template_name='catalog/availablesoftware.html'
    paginate_by = 10
    def get_queryset(self):
        return Software.objects.order_by('title')

class SoftwareRequestsManager(LoginRequiredMixin, generic.ListView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = RequestingSoftware
    template_name='catalog/requstsoftwaremanager.html'
    paginate_by = 10
    def get_queryset(self):
        return RequestingSoftware.objects.order_by('send_date')

#manage software
class SoftwareManager(LoginRequiredMixin, generic.ListView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = Software
    template_name='catalog/softwaremanager.html'
    paginate_by = 10
    def get_queryset(self):
        return Software.objects.order_by('title')
        
class CreateSoftware(LoginRequiredMixin, CreateView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = Software
    fields = ['title', 'description']
    success_url = reverse_lazy('software-manager')

class UpdateSoftware(LoginRequiredMixin,UpdateView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = Software
    success_url = reverse_lazy('software-manager')
    fields = ['title', 'description']

class DeleteSoftware(LoginRequiredMixin, DeleteView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = Software
    success_url = reverse_lazy('software-manager')


#manage software instance
class CreateSoftwareInstance(LoginRequiredMixin, CreateView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = SoftwareInstance
    fields = ['license_key', 'renewal_date', 'renewal_cost']
    success_url = reverse_lazy('mysoftware')

    def form_valid(self, form):
        return super(CreateSoftwareInstance, self).form_valid(form)

class UpdateSoftwareInstance(LoginRequiredMixin, UpdateView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = SoftwareInstance
    fields = ['license_key', 'renewal_date', 'renewal_cost', 'status', 'user']
    success_url = reverse_lazy('mysoftware')

class DeleteSoftwareInstance(LoginRequiredMixin, DeleteView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = SoftwareInstance
    success_url = reverse_lazy('mysoftware')

    




class SoftwareDetailView(LoginRequiredMixin, generic.DetailView):
    model = Software

class SoftwareRequestsDetailView(LoginRequiredMixin, generic.DetailView):
    model = RequestingSoftware

class CreateSoftwareRequest (LoginRequiredMixin, CreateView, PermissionRequiredMixin):
    template_name='catalog/requestingsoftware_form.html'
    permission_required = 'catalog.canmake'
    model = RequestingSoftware
    fields = ['name', 'email', 'department', 'software', 'reason']    
    success_url = reverse_lazy('softwarerequest-create')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateSoftwareRequest, self).form_valid(form)

class DeleteRequestingSoftware(LoginRequiredMixin, DeleteView, PermissionRequiredMixin):
    permission_required = 'catalog.canmake'
    model = RequestingSoftware
    success_url = reverse_lazy('softwarerequests-manager')

@login_required
@permission_required('catalog.canmake', raise_exception=True)
def accept_button(request, pk):
    requestingsoftware_instance = get_object_or_404(RequestingSoftware, pk=pk)
    context = {
        'requestingsoftware_instance': requestingsoftware_instance,
    }
    
    request.session['RequestingSoftware'] = str(requestingsoftware_instance.id)

    return render(request, 'catalog/requestingsoftware_confirm_accept.html',context)
    
@login_required
@permission_required('catalog.canmake', raise_exception=True)
def process(request, pk):
    if not get_referer(request):
        return HttpResponse('<h1>Page not found</h1>')
    Softwarerequest = RequestingSoftware.objects.get(id=request.session['RequestingSoftware'])
    del request.session['RequestingSoftware']
    softwareinstance = get_object_or_404(SoftwareInstance, pk=pk)
    softwareinstance.user = Softwarerequest.user
    softwareinstance.status = 'u'
    softwareinstance.save()
    Softwarerequest.delete()
    return redirect('softwarerequests-manager')

@login_required
@permission_required('catalog.canmake', raise_exception=True)
def softwarelicensekeys(request, pk):
    software = get_object_or_404(Software, pk=pk)

    context = {
        'software' : software,
        'softwareinstance_list': software.softwareinstance_set.all,
    }
    return render(request, 'catalog/mysoftware.html',context)

"""
def accept_button(request, pk):
    requestingsoftware_instance = get_object_or_404(RequestingSoftware, pk=pk)

    if request.method == 'POST':
        form = ApplyLicenseKeyForm(request.POST)
        if form.is_valid():
            requestingsoftware_instance = get_object_or_404(RequestingSoftware, pk=pk)
            requestingsoftware_instance.save()
            requestingsoftware_instance.delete()
            return redirect('softwarerequests-manager')
    else:
        form = ApplyLicenseKeyForm(requestingsoftware_instance.software)

    context = {
        'form': form,
        'requestingsoftware_instance': requestingsoftware_instance,
    }

    return render(request, 'catalog/requestingsoftware_confirm_accept.html',context)

"""

catalog/templates/catalog/availablesoftware.html
{% extends 'account/base.html' %}

{% block content %}
<div class="text-center">
  <ul>

  <h1>Available Software</h1>

  {% if software_list %}

    {% for soft in  software_list%}
      <p>   {{soft.title}} <a href="{% url 'software-detail' soft.pk %}"> <br> Description</a> 
  <br> </p>
    {% endfor %}

  {% else %}
    <p>You have no available software</p>
  {% endif %}

</ul>

</div>
    
{% endblock %}

catalog/templates/catalog/availablesoftwarelicense.html
{% extends 'account/base.html' %}

{% block content %}
<div class="text-center">
  <ul>

  <h1>Software Liscene Keys</h1>

  {% if software_list %}

    {% for soft in  software_list%}
      <p>   {{soft.title}}'s <a href="{% url 'mysoftware-instances' soft.pk %}"> License Keys</a> <br>  
  <br> </p>
    {% endfor %}

  {% else %}
    <p>You have no available software</p>
  {% endif %}

</ul>

</div>
    
{% endblock %}

catalog/templates/catalog/mysoftware.html
{% extends 'account/base.html' %}

{% block content %}
  <ul>
  <h3> A list of license keys for {{software}}</h3>
  <p>(red means the license key is past renewal date)</p>
  {% if softwareinstance_list %}

    {% for softinst in  softwareinstance_list%}
    <li class="{% if softinst.is_overdue %} text-danger {% endif %}"> 
      License Key: {{ softinst.license_key}}
      <br> Renewal Date: {{ softinst.renewal_date }} 
      <br> Renewal Cost: {{softinst.renewal_cost}} 
      <br> User: {{softinst.user}}
      <br> Status:  {% if softinst.is_available %} Available {% else %} In use  {% endif %}
      <br><a href="{% url 'softwareinstance-update' softinst.pk %}">Update</a>
      <a href="{% url 'softwareinstance-delete' softinst.pk %}">Remove <br></a></p> </li>
     
    {% endfor %}

  {% else %}
    <p>No existing license keys. Add one in Manager Actions.</p>
  {% endif %}
</ul>

    
{% endblock %}

catalog/templates/catalog/requestingsoftware_confirm_accept.html
{% extends 'account/base.html' %}

{% block content %}
<ul>
<p>Select the license key for {{requestingsoftware_instance.software}} you wish to send to {{requestingsoftware_instance.name}}</p>
    {% if requestingsoftware_instance.software.softwareinstance_set.all %}
    {% if requestingsoftware_instance.any_avaiable %}
    {% for copy in requestingsoftware_instance.software.softwareinstance_set.all %}
        {% if not copy.is_overdue %}
            {% if copy.is_available %}
                <p> Available License Key: <a href="{% url 'softwarerequests-forward' copy.pk %}">  {{ copy.license_key }} </a>  <br> Renewal Date: {{copy.renewal_date}}</p>
        {% endif %}
        {% endif %}
    {% endfor %}
    {% else %}
        <p>No available license keys</p>
    {% endif %}
    {% endif %}

</ul>
{% endblock %}

catalog/templates/catalog/requestingsoftware_confirm_delete.html
{% extends 'account/base.html' %}

{% block content %}
<ul>
<p>Are sure you want to decline the request for {{requestingsoftware.software}} by {{requestingsoftware.name}}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes">
</form>
</ul>
{% endblock %}

catalog/templates/catalog/requestingsoftware_detail.html
{% extends 'account/base.html' %}

{% block content %}
<ul>
  <h1>Name: {{ requestingsoftware.name }}</h1>
  <h4>Department: {{ requestingsoftware.department }}</h4>
  <h4>Contact Email: {{ requestingsoftware.email }}</h4>
  <h4>Account Email: {{ requestingsoftware.user.email }}</h4>
  <h4>Software Requested: {{ requestingsoftware.software }}</h4>
  <h4>Associated License Keys for {{requestingsoftware.software}}: </h4>
  {% if requestingsoftware.software.softwareinstance_set.all %}
    {% for copy in requestingsoftware.software.softwareinstance_set.all %}
        {% if copy.is_overdue %}
        <div class="text-danger"> <p> Overdue License Key: {{ copy.license_key }} Renewal Cost: {{copy.renewal_cost}}</p> </div>
        {% else %}
            <p> Available License Key: {{ copy.license_key }}</p>
        {% endif %}
    {% endfor %}
    {% else %}
        <p>No available license keys</p>
  {% endif %}


  <p><strong>Reason for Request:</strong> {{ requestingsoftware.reason }}</p>

</ul>
{% endblock %}

catalog/templates/catalog/requestingsoftware_form.html
{% extends 'account/base.html' %}

{% block content %}
<ul>
<h2>Software Request</h2>
<p> Fill out the form to submit a software request</p>
<form action="" method="post">
  {% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>
</ul>
{% endblock %}

catalog/templates/catalog/requstsoftwaremanager.html
{% extends 'account/base.html' %}

{% block content %}
<div class="text-center">
  <ul>

  <h1> Pending Software Requests</h1>

  {% if requestingsoftware_list %}

    {% for soft in  requestingsoftware_list%}
      <p>  {{soft.name}} from {{soft.department}} is requesting {{soft.software.title}} <a href="{% url 'softwarerequests-detail' soft.id %}"> <br> Details</a> 
        <a href="{% url 'softwarerequests-accept' soft.id %}"> <br> Approve</a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="{% url 'softwarerequests-decline' soft.id %}">  Decline</a> </p>
    {% endfor %}

  {% else %}
    <p>You have no pending software requests</p>
  {% endif %}

</ul>

</div>
    
{% endblock %}

catalog/templates/catalog/software_confirm_delete.html
{% extends 'account/base.html' %}

{% block content %}
<ul>
<h1>Delete Software</h1>

<p>Are you sure you want to delete the software: {{ software }}? (ALL instances of {{ software }} will be deleted)</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes">
</form>
</ul>
{% endblock %}

catalog/templates/catalog/software_detail.html
{% extends 'account/base.html' %}

{% block content %}
<ul>
  <h1>Title: {{ software.title }}</h1>

  <p><strong>Description:</strong> {{ software.description }}</p>

</ul>
{% endblock %}

catalog/templates/catalog/software_form.html
{% extends 'account/base.html' %}

{% block content %}
<ul>
<form action="" method="post">
  {% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>
</ul>
{% endblock %}

catalog/templates/catalog/softwareinstance_confirm_delete.html
{% extends 'account/base.html' %}

{% block content %}
<ul>
<h1>Remove </h1>

<p> Do you wish to remove the following license key: {{softwareinstance.license_key}} </p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes">
</form>
<br> 
<a href="{% url 'availablesoftware' %}">  
  <input type="submit" value = "No"/>

 </a>
</ul>
{% endblock %}

catalog/templates/catalog/softwareinstance_form.html
{% extends 'account/base.html' %}

{% block content %}
<ul> 
<form action="" method="post">
  {% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>
</ul>
{% endblock %}

catalog/templates/catalog/softwaremanager.html
{% extends 'account/base.html' %}

{% block content %}
  
  {% if software_list %}
  <ul>
    <h1>Software Manager</h1>
    <h5>Edit the available softwares</h5>

    {% for soft in  software_list%}
      <p>{{soft.title}} <br> <a href="{% url 'software-update' soft.id %}">Update</a>
        <a href="{% url 'software-delete' soft.id %}">Delete <br></a></p>

    {% endfor %}
   
  </ul>

  {% else %}
    <p>You have no available software</p>
  {% endif %}
  <ul>
  <h3>Add a new available software</h3>
  <a href="{% url 'software-create'%}">Add Software</a> 
  <h3> <br>Add a license key to a software</h3>
<a href="{% url 'softwareinstance-create'%}">Add License Key</a> 
  </ul>
    
{% endblock %}